# Generated by Django 6.0 on 2025-12-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.PositiveIntegerField(unique=True)),
                ('sepal_length', models.FloatField()),
                ('sepal_width', models.FloatField()),
                ('petal_length', models.FloatField()),
                ('petal_width', models.FloatField()),
                ('species', models.CharField(choices=[('setosa', 'Iris setosa'), ('versicolor', 'Iris versicolor'), ('virginica', 'Iris virginica')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('public', models.BooleanField(default=False)),
                ('samples', models.ManyToManyField(blank=True, related_name='collections', to='gallery.irissample')),
            ],
        ),
    ]
